server:
  port: 8100
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/learniteasy/common-config
          search-paths: 
          - '*config'

          
          
